### ISSUE TITLE
Xwayland zombies

### ISSUE THREAD

**Issue by martinetd** [SirCmpwn/wlroots#122]
Currently if Xwayland crashes or gets killed, we will start a new Xwayland and recover back to useable state but will never attempt to reap the process, leaving a zombie behind.

The shutdown code cannot do a waitpid() call, because for example on normal Xwayland shutdown it will tell us to destroy the wl client before the process ends, so we would just deadlock.

I can see two alternatives to reap this properly: 
 * Either have an handler for SIGCHLD, this would not be xwayland specific but we could just reap stuff as they come and eventually have a list of actions for specific pid deaths (weston does that)
 * We could say we never will care about that process and double-fork to spawn Xwayland. It will then be taken by init and reaped whenever it dies - we will still get the notification from its wayland client being destroyed as we do now, so for all intent and purpose it will work for us.
The only thing we lose is that we will no longer know what pid Xwayland is started as - but while we store that information we never use it so it isn't a big loss.

Thoughts?

**Comment by SirCmpwn** [comment]
Double fork seems like a good approach to me. What do you think?

**Comment by martinetd** [comment]
Yeah, definitely simplest way around. I hadn't thought of it until earlier today or I probably would have done that.
I'll whip that up and push something at some point this weekend
