### ISSUE TITLE
Output layout autoconfiguration

### ISSUE THREAD

**Issue by acrisci** [SirCmpwn/wlroots#127]
An auto configured output is positioned in a sensible place on the screen. The user does not specify coordinates for an auto configured output, rather the coordinates are adjusted dynamically whenever the layout changes. An output that is not auto configured is called manually configured.

The use case is for compositors that don't want to require user configuration for outputs within the layout.

Auto configuration is presently implemented in `examples/config.c:configure_layout()` but should be moved into wlroots.

```c
/**
* Add an auto configured output to the layout. This will place the output in a
* sensible location in the layout. The coordinates of the output in the layout
* may adjust dynamically when the layout changes. If the output is already in
* the layout, it will become auto configured. If the position of the output is
* set such as with `wlr_output_layout_move()`, the output will become manually
* configured.
*/
void wlr_output_layout_add_auto(struct wlr_output_layout *layout, struct wlr_output *output);
```

**Comment by acrisci** [comment]
Maybe the auto configuration strategy should be configurable. Right now it adds all the outputs to the right of the rightmost output, but users might want to add the outputs to the left, above, below, or something else.

**Comment by SirCmpwn** [comment]
Not very important IMO. They can just manually arrange them at that point.
