### ISSUE TITLE
GLES2 support

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#13]
I recently tried using wlroots on my laptop with an Intel iGPU (i5-520M is the CPU, not really sure what the iGPU name is), and it currently doesn't work.
It turns out this hardware doesn't support GLES 3, and only goes up as high as GLES 2.
While this laptop is getting on a bit in terms of age, it would be nice for wlroots to be able to support older hardware.

So I think we should either downgrade the current renderer to GLES 2 or create a separate GLES 2 fallback when we can't load GLES 3.

**Comment by SirCmpwn** [comment]
Alright, we can go for GLES 2.

**Comment by SirCmpwn** [comment]
When working on this we should also try to expose the GLES2 internals some more.

**Comment by SirCmpwn** [comment]
So it looks like GLES2 doesn't support VBOs. I think we should have both renderers and choose the best supported one.

**Comment by SirCmpwn** [comment]
Decided against maintaining two rendering backends. VBOs are nice but I'm not sure we're really going to gain much from them.
