### ISSUE TITLE
give compositor.c example reference implmentation status

### ISSUE THREAD

**Issue by acrisci** [SirCmpwn/wlroots#150]
The term "compositor" seems to be heavily overloaded and it's leading to some confusion with the term.

The compositor.c seems to becoming our reference implementation because all the new features are being integrated with it. So I suggest we give the project a real name and official reference implementation status that people can use like documentation.

My suggestion is to call it "rootston" but you might think that's dumb.

**Comment by SirCmpwn** [comment]
I do think that's dumb, but I also like it :) Are you thinking we should move it out of tree?

**Comment by acrisci** [comment]
I like how the implementation and the library changes are in the same commits because they sort of become like our tests. It makes development easier to follow.

**Comment by SirCmpwn** [comment]
Fair. It might make sense to promote it out of the examples directory, though.

**Comment by acrisci** [comment]
I agree. The shared.c needs to be reorganized as well. I think it should be possible to copy/paste it out of the tree and use that as the basis for organizing a port or new project.

**Comment by SirCmpwn** [comment]
It may be wise to simply rewrite the compositor from scratch with the benefit of hindsight.

**Comment by acrisci** [comment]
superceded by #168
