### ISSUE TITLE
Proposal: Split backends into their own shared objects

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#174]
I was thinking about the customisability and extendibility of wlroots' design, and as it is now, all of the customisability happens at build time.
I was thinking we could try let it happen at runtime too. This is basically what weston does.

# Proposal
Have each backend (drm/libinput, wayland, x11, others) be built as their own separate shared objects.
Install them into /usr/lib/wlroots or something like that.
Detect and load the required backend at runtime.

## Advantages
- Easier for distribution packages to have optional dependencies. Someone can easily choose not to install "wlroots-backend-x11", and they don't need to rebuild wlroots.
- Easier for other people to write wlroots backends out-of-tree, and not require any code from compositors to explicitly load them.
- Have the ability to explicitly load any backend via an environment variable or a config option.

## Disadvantages
- A bit more shit to do to load the shared objects, as we'll have to dlsym ourselves.
- A slight performance penalty. But since we're already using functions pointers for out backends, which already causes them to not be inlineable, it may not actually make any difference.
- We have to be more rigid with our internal backend API, but we should probably do that anyway.

The backends are already pretty self-contained, so I don't think it would be a huge amount of effort to do this.

**Comment by SirCmpwn** [comment]
To be honest, I *really* dislike this approach. Sorry.

**Comment by ascent12** [comment]
Meh, whatever. It's not something I was pushing very hard.

**Comment by SirCmpwn** [comment]
On the other hand, I think it would be great to install separate wlr libraries as separate static libraries.

**Comment by ascent12** [comment]
Static libraries don't solve the problem that this was going for.

**Comment by SirCmpwn** [comment]
I know, but it solves a similar problem imo.
