### ISSUE TITLE
-Wlto-type-mismatch

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#26]
Building wlroots with link time optimisation (-flto) causes this error to be raised by GCC.
It's being caused by the whole overloaded "wlr_backend_state" thing, where it had multiple, different definitions.

I feel we should change how all of that is handled, so we can safely build with LTO.

**Comment by SirCmpwn** [comment]
Is this an error or a warning? Because if it's the latter we can suppress it with the knowledge that we know better.

**Comment by SirCmpwn** [comment]
I'm willing to consider a proposal for an alternative design, but I'm pretty happy with the current approach.

**Comment by ascent12** [comment]
It is just a warning, but I don't know if this is the sort of thing that is going to cause the compiler to output incorrect code.

I would prefer a design like what we currently use for the session code (and what weston does).
```c
struct some_backend {
    struct wlr_backend base;
    // More fields
}

void some_function(struct wlr_backend *base) {
    struct some_backend *backend = wl_container_of(base, backend, base);

    // Continue as normal
}
```
It allows types to not even need to be known of outside of their modules.
It would be pretty easy to change to this as well.

**Comment by SirCmpwn** [comment]
`wl_container_of` is way hackier than the current system.

**Comment by ascent12** [comment]
>wl_container_of is way hackier than the current system.

Yeah, pointer casts of struct members are somewhat hacky, but it's not an uncommon thing you see in a lot of projects so compilers deal with it fine.
Due to the way the wayland library is designed, `wl_container_of` is unavoidable, so it's not like we're introducing some "new" hacky way of writing code.

I also feel it's less misleading to any new people who might drop in and read the code. Usually one of the earliest things I would look at is the types, and I would think it's confusing/weird as hell if there were multiple (and different) definitions of the same time.

**Comment by SirCmpwn** [comment]
I don't think I'm any more convinced than the last time you complained about this design to be honest.

**Comment by ascent12** [comment]
Well, my argument hasn't really changed at all, but now GCC's LTO is complaining about it.

There are other possibilities, such as tagged unions, but it would be a lot more rigid that the current/proposed design.

I just think `wl_container_of` would be the cleanest design.

**Comment by nyorain** [comment]
Is ```wl_container_of``` even really needed if implementing it like ascent proposed?
afaik, the c standard guarantees that the following (basically the common c inheritance idiom) is valid (if the given ```wlr_backend``` really is a ```some_backend```), doesn't it? There cannot be any padding before the first member.
```c
struct some_backend {
    struct wlr_backend base;
    // More fields
}

void some_function(struct wlr_backend *base) {
    struct some_backend *backend = (struct some_backend *)base;

    // Continue as normal
}
```
I feel like ascent's approach would be at least more conventional and common than the current implementation. It would probably also simplify things, one allocation less per polymorphic object (state and base object are the same) and not the struggle of maybe holding a pointer in the ```*_state``` class pointing back to the base object, so the design would be more clear as well i guess.

**Comment by SirCmpwn** [comment]
Shoving the entire wlr_backend in here is silly. I'm sick of this discussion, I like the current approach and that's that.

**Comment by ascent12** [comment]
GCC's LTO is still complaining, which is the real issue.

**Comment by ascent12** [comment]
This is a bit of a text dump, but I'm trying to be precise with my reasoning.
http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1570.pdf

> **Section 6.2.7 Compatible type and composite type**
> Two types have compatible type if their types are the same.  [...] Moreover,
> two structure, union, or enumerated types declared in separate translation
> units are compatible if their tags and members satisfy the following
> requirements: If one is declared with a tag, the other shall be declared with
> the same tag. If both are completed anywhere within their respective
> translation units, then the following additional requirements apply: there
> shall be a one-to-one correspondence between their members such that each pair
> of corresponding members are declared with compatible types; if one member of
> the pair is declared with an alignment specifier, the other is declared with an
> equivalent alignment specifier; and if one member of the pair is declared with
> a name, the other is declared with the same name. For two structures,
> corresponding members shall be declared in the same order.

We definitely fail this. All of the `wlr_backend_state`s are incompatible with each other.

> **Section 6.5.2.2 Function calls**
> An argument may be an expression of any complete object type. In preparing for
> the call to a function, the arguments are evaluated, and each parameter is
> assigned the value of the corresponding argument.

> **Section 6.5.16.1 Simple assignment**
> One of the following shall hold:
> - the left operand has atomic, qualified, or unqualified arithmetic type, and the
> right has arithmetic type;
> - the left operand has an atomic, qualified, or unqualified version of a
> structure or union type compatible with the type of the right;
> - the left operand has atomic, qualified, or unqualified pointer type, and
> (considering the type the left operand would have after lvalue conversion) both
> operands are pointers to qualified or unqualified versions of compatible types,
> and the type pointed to by the left has all the qualifiers of the type pointed
> to by the right;
> - the left operand has atomic, qualified, or unqualified pointer type, and
> (considering the type the left operand would have after lvalue conversion) one
> operand is a pointer to an object type, and the other is a pointer to a
> qualified or unqualified version of void , and the type pointed to by the left
> has all the qualifiers of the type pointed to by the right;
> - the left operand is an atomic, qualified, or unqualified pointer, and the right
> is a null pointer constant; or
> - the left operand has type atomic, qualified, or unqualified _Bool , and the
> right is a pointer.

None of these hold. The third one is the only relevant one, but the types are incompatible.

> **Annex J**
> **Section J.2 Undefined behavior**
> - A ‘‘shall’’ or ‘‘shall not’’ requirement that appears outside of a constraint
> is violated (clause 4).
> - Two pointer types that are required to be compatible are not
> identically qualified, or are not pointers to compatible types (6.7.3).

It's undefined behavior, and GCC is completely right to complain.
Boiling the problem down, it's really just
```c
struct a *a = whatever;
struct b *b = a;
```

I don't want to hear any "we know better than the compiler/standard" crap.
This is invalid code, can easily cause misoptimisations, all for what are basically some 
"fake" void pointers.

**Comment by SirCmpwn** [comment]
We never assign across conflicting types like you're describing. If I'm interpreting the text you dumped correctly, we are not invoking undefined behavior.

**Comment by ascent12** [comment]
The setting of function arguments are defined though assignment.

**Comment by SirCmpwn** [comment]
FIne, we'll fucking change it.

**Comment by SirCmpwn** [comment]
Update: this is in progress. I've refactored out wlr_backend_state and wlr_output_state. If anyone wants to follow my lead with a PR updating other types, I would appreciate that.

**Comment by martinetd** [comment]
Will do some of these.
As far as I can see we have these left:
 - wlr_texture_state
 - wlr_renderer_state
 - wlr_input_device_state
 - wlr_keyboard_state
 - wlr_pointer_state
 - wlr_tablet_pad_state
 - wlr_tablet_tool_state
 - wlr_touch_state
 - wlr_output_mode_state

I'll start with the input ones as I have already messed with it quite a bit (everything from input_device to touch), if someone else wants to do the last three.

**Comment by SirCmpwn** [comment]
I'll take the other three, I should be able to get them done before work.
