### ISSUE TITLE
[Proposal] Remove wlr-render, replace with cairo

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#32]
I was looking around the cairo headers lately, and I found out that cairo can render to GL surfaces (using GLESv2) and create it from EGLDisplays and EGLSurfaces. Their documentation seems to be pretty old and doesn't contain the functions, but you can find them in <cairo/cairo-gl.h>.

I figured instead of having to do anything ourselves and try to design some drawing API, we just tell the user to use this. Cairo can seem to do all of the transformations required, and already is used by sway and probably most wayland compositors.

We don't even need to explicitly support cairo or have it as a dependency (excluding the examples): as long as we expose the EGLDisplay and EGLSurface (which I'm sure we would do anyway), the user can make their own cairo surface or do whatever the hell they want (use some other drawing API, roll their own GL renderer, etc.).

**Comment by SirCmpwn** [comment]
I'd like to leave wlr-render in place but I also don't mind exposing our EGLDisplay and EGLSurfaces so that compositors could use cairo.

**Comment by SirCmpwn** [comment]
Folding this into #14.
