### ISSUE TITLE
[proposal] Common user interface for mode switching

### ISSUE THREAD

**Issue by acrisci** [SirCmpwn/wlroots#38]
It would be convenient if wlroots-based compositors could share some tooling for things they would almost certainly implement themselves. Switching monitor modes and positions at runtime is a core feature that everybody uses on the linux desktop.

What's really nice about X is that we have a common way to do these things. No matter what DE I use, I can set up my monitor with tools like `xrandr` and `arandr`.

I propose that we set up a dbus interface with methods that can configure monitors. Then someone could write an equivalent `arandr` for wlroots compositors that could be shared between the projects.

**Comment by SirCmpwn** [comment]
I'm not opposed to this, but *not* via dbus. We can add an implementation of the KDE modesetting Wayland protocol for compositors to use.

**Comment by SirCmpwn** [comment]
We should also consider standardizing a permissions model for this sort of thing.

**Comment by acrisci** [comment]
This might do it:

https://cgit.freedesktop.org/wayland/wayland-protocols/commit/?id=794a96a80fe16885288a784adad6f9d12957439a

**Comment by SirCmpwn** [comment]
This is a read-only interface, it's not used for modesetting.
