### ISSUE TITLE
gles2 surface should destroy previous texture resources when replacing them

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/wlroots#47]

**Comment by nyorain** [comment]
So i guess this is fixed now? The previous texture is not destroyed but reused instead.

**Comment by SirCmpwn** [comment]
No, `gles2_texture_upload_{pixels,shm}` still calls `gles2_texture_gen_texture` to gen new textures without releasing or reusing the old ones.

**Comment by nyorain** [comment]
the function simply returns if the texture was already created... ```gles2_texture_assure_texture``` or something like this may be a better name
