### ISSUE TITLE
Transparent surfaces do not render transparently

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/wlroots#56]
Not sure what the problem is, enabling GL_BLEND and configuring the glBlendFunc does not seem to do the trick.

**Comment by SirCmpwn** [comment]
I've been using `weston-simple-damage` as a reference client for this problem, btw

**Comment by acrisci** [comment]
I'll work on this. `weston-image` and `west-flower` have transparent regions as well.
