### ISSUE TITLE
wlroots rotation exits after hot-unplugging

### ISSUE THREAD

**Issue by Ongy** [SirCmpwn/wlroots#61]
I tested hotplugging the VGA-1 output on my Intel HD 3000.

Plugging it in while `./build/examples/rotation` is running is detected, and the display is used.

Unplugging it shuts down the application after a few seconds. Here is a [log](https://gist.github.com/Ongy/c230332f95ea5ffc48e8409fe57811cc) of plugging the display in and unplugging.
It does not make a difference, whether the display was plugged in when starting rotation, or got plugged in while rotation is running.

**Comment by ascent12** [comment]
It's probably crashing. There was an issue with a possible null pointer dereference that can happen when a monitor is unplugged and was fixed in fe2fbd0fad96624ab64a86b0b8eb8ead769908f2.
Can you test master now and see if it fixes it for you?

**Comment by Ongy** [comment]
Looks good to me. I can unplug while it is running now.
Bot hotplug and hotunplug now work. Repeated and when monitor is plugged in when started and when it's unplugged.
