### ISSUE TITLE
Finish moving wayland components from example into wlroots

### ISSUE THREAD

**Issue by SirCmpwn** [SirCmpwn/wlroots#67]
`examples/compositor/wl_{compositor,shell}.c` -> `types/wlc_{compositor,shell}.c`

I've decided against making the user implement all of these themselves. These are simple state containers and putting them in wlroots is not a big deal. I've already performed this move for `xdg-shell`, check out https://github.com/SirCmpwn/wlroots/commit/62d8b252c093b3bd71362b1c76cb70b16a6cd63a for an idea of how (if you can read around all the meson changes).

**Comment by acrisci** [comment]
Mostly fixed in Rootston.
