### ISSUE TITLE
User data usage in examples/compositor/wl_compositor.c

### ISSUE THREAD

**Issue by 4e554c4c** [SirCmpwn/wlroots#71]
`wl_compositor.c` stores data in the `wlr_surface` struct. It should not do this as it will soon be merged into wlroots, and the data field in wlr_surface is to be changed by the user only.

**Comment by nyorain** [comment]
you're right. It's only there as long as we use wl_compositor to iterate over the created surfaces since it needs this data to keep track of surface destruction.

**Comment by SirCmpwn** [comment]
I'll sort this tonight or this weekend.

**Comment by acrisci** [comment]
I did a review and I guess we fixed it.
