### ISSUE TITLE
alloc error handling

### ISSUE THREAD

**Issue by nyorain** [SirCmpwn/wlroots#76]
In some places wlroots check if an alloc function returns NULL, in others it does not (and will simply crash).
In most places when alloc returns NULL things are going to blow up anyways (or things are getting weird), i guess the best thing to do would output an error and exit.
We could remove a lot of repetitive checks and boilerplate and at the same time transform in other places a segmentation fault on alloc error into an error message and exit by introducing a macro/function that simply logs the allocation error and exits on failure and otherwise is guaranteed to return a valid pointer.
[This](https://github.com/wayland-project/weston/blob/master/shared/xalloc.h) is how weston does it, would something like this be acceptable in wlroots?

**Comment by ascent12** [comment]
I'm normally against the idea of a library aborting a program for the user. It feels like it can go against the expectations of the user.

Maybe OOM is a serious/rare enough issue where you can just say that there really isn't anything sane you can do. With the way wlroots is designed though, it would be viable to fall back to the event loop and just try again later, but it may be difficult trying to keep the program state consistent.

That's also not mentioning that Linux lies about allocations and may return non-NULL even if it doesn't have any real memory backing it.

**Comment by SirCmpwn** [comment]
To be entirely honest, I don't really care about malloc failures. I don't think we have a situation where it could fail under reasonable circumstances. I think the appropriate way is to make any function that does allocations have a way of communicating errors, then bubble it up.

**Comment by FSMaxB** [comment]
Malloc can reasonably fail when requesting huge allocations. And under some circumstances that can happen based on userdata. For example huge texture allocations or something like that (there is probably some way that a client could request a large resource from the compositor who the passes it on to wlroots).

**Comment by SirCmpwn** [comment]
>requesting huge allocations

We don't

>huge texture allocations or something like that

This happens on the GPU and we already handle failure, we don't actually malloc anything

**Comment by FSMaxB** [comment]
Another possibility is an underflow in the requested size.

**Comment by SirCmpwn** [comment]
That's a serious bug in its own right, not something we can really prepare for.

**Comment by SirCmpwn** [comment]
I'm pretty sure we don't actually malloc anything that doesn't use sizeof (aside from strdup, w/e)

**Comment by ascent12** [comment]
I'm fine with this going ahead, but only for OOM situations. exit() shouldn't be the catch-all error handler.

If someone is going to implement this, make sure to do strdup and maybe an asprintf version (easy to do with snprintf, GNU not needed).

**Comment by SirCmpwn** [comment]
I don't want to see a macro based approach. I just want to find places we allocate memory and handle them appropriately.

**Comment by ascent12** [comment]
Macros are completely unnecessary for this. It works fine as a normal function.
```c
void *xalloc(size_t size) {
    void *ptr = malloc(size);
    if (!ptr) {
        wlr_log_errno(L_ERROR, "Allocation of size %zu failed", size);
        exit(1);
    }
    return ptr;
}
```
All call exactly like you would with malloc.

**Comment by SirCmpwn** [comment]
Ehhh... we definitely should not exit, but the logging may be useful. Not sure if it's useful enough to convince me it's worthwhile, though.

**Comment by ascent12** [comment]
I thought exiting was the whole point of this, otherwise this is basically no different that what we're doing now.

**Comment by SirCmpwn** [comment]
I guess the main thing remaining in this ticket is

>In some places wlroots check if an alloc function returns NULL, in others it does not (and will simply crash).

Well, where does it crash? Let's fix it.

**Comment by 4e554c4c** [comment]
For those interested I'm working on passing alloc errors down instead of just crashing
