### ISSUE TITLE
Cache surface dimensions on surface.attach

### ISSUE THREAD

**Issue by acrisci** [SirCmpwn/wlroots#89]
According to the spec, when surface.attach is called in the wl_surface interface implementation,

> The new size of the surface is calculated based on the buffer size transformed by the inverse buffer_transform and the inverse buffer_scale.

Right now this calculation is done on surface.commit but it should be moved.

**Comment by SirCmpwn** [comment]
What happens when someone attaches and then changes the transform before committing?

**Comment by acrisci** [comment]
I just talked to people in wayland chat about this and it appears that I misread the spec. I confirmed that in the weston codebase as well. So I don't think this is necessary after all.
