### ISSUE TITLE
Code consistency

### ISSUE THREAD

**Issue by ascent12** [SirCmpwn/wlroots#93]
Jumping around the code a bit, I can see a few different styles for how different things are handled, particularly error messages, and how certain situations are handled.
These currently aren't covered by CONTRIBUTING.md, so I think we should expand it.

### Error Messages

There are several different formats being used, ranging from "Cannot X, reason", "Failed to X: reason", "X failed: reason", etc.
We should mandate that a single style is used. More use of wlr_log_errno (where appropriate) would help.

### Assertions

There are a few non-NULL asserts around. We should use them more consistently, at least over the public API.
On a related note, any "destruction" function should be able to accept a NULL pointer and exit gracefully, which simplifies error handling a lot.

### Function names

We seem to have functions named *_init, *_create, *_finish, *_destroy. While it's mostly like this already (but not fully), we should document that init/finish should NOT handle allocations, and create/destroy do.

**Comment by SirCmpwn** [comment]
All of these are correct, though I'm not too picky about error message consistency.

**Comment by acrisci** [comment]
The rule of one tab after multi-line functions is inconsistent too.

**Comment by SirCmpwn** [comment]
It's two tabs after multi-line declarations and one tab after multi-line calls.

**Comment by martinetd** [comment]
Not doing this because I'm in the middle of something else (I might later, but feel free to if someone else is doing cleanups), but:
 - struct wl_signal should be in an "events" substruct
These need fixing: include/backend/udev.h, include/wlr/backend/session.h, include/wlr/types/wlr_surface.h, and include/wlr/render.h

**Comment by ascent12** [comment]
It's a pretty minor point, the names we use for include guards is a bit all over the place. It ranges from DRM_BACKEND_H to _WLR_BACKEND_LIBINPUT_INTERNAL_H.

I would suggest we just take the file path relative to include/ and just uppercase everything and replace bad characters with underscores (/, -, . etc.).
include/backend/libinput.h becomes BACKEND_LIBINPUT_H, include/wlr/types/wlr_box.h becomes WLR_TYPES_WLR_BOX_H, etc.
